project_name: node-pod
release:
  github:
    owner: mattfenwick
    name: krew-node-pod
builds:
  - id: node-pod
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/mattfenwick/krew-node-pod/pkg/version.version=
archives:
  - id: node-pod
    builds:
    - node-pod
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
