apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-pod
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/mattfenwick/krew-node-pod/releases/download/v0.1.0/kubectl-node_pod_linux_amd64.tar.gz
    sha256: "c21488a37c7a29b43c22cf078c772858f1380d7836eaddeaf34a171fa405a821"
    files:
    - from: "./kubectl-node_pod"
      to: "node-pod"
    - from: LICENSE
      to: "."
    bin: "node-pod"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/mattfenwick/krew-node-pod/releases/download/v0.1.0/kubectl-node_pod_darwin_amd64.tar.gz
    sha256: "1a7357f9532dd0cae163a938f0bde483567093f489b508547fac4bccdc725306"
    files:
    - from: "./kubectl-node_pod"
      to: "node-pod"
    - from: LICENSE
      to: "."
    bin: "node-pod"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/mattfenwick/krew-node-pod/releases/download/v0.1.0/kubectl-node_pod_windows_amd64.zip
    sha256: "fde3fc66ffb7f0128748a4156ce26bbaf02d63fa9cc9d7d5f6bccc33bda7b8f3"
    files:
    - from: "/kubectl-node_pod.exe"
      to: "node-pod.exe"
    - from: LICENSE
      to: "."
    bin: "node-pod.exe"
  shortDescription: Shows assignment of pods to nodes.
  homepage: https://github.com/mattfenwick/krew-node-pod
  caveats: |
    Usage:
      $ kubectl node-pod

    For additional options:
      $ kubectl node-pod --help
      or https://github.com/mattfenwick/krew-node-pod/blob/v0.1.0/doc/USAGE.md

  description: |
    This plugin shows the assignment of pods to nodes.
