apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: node-pod
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/mattfenwick/krew-node-pod/releases/download/v0.1.0/node-pod_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./node-pod"
      to: "."
    - from: LICENSE
      to: "."
    bin: "node-pod"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/mattfenwick/krew-node-pod/releases/download/v0.1.0/node-pod_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./node-pod"
      to: "."
    - from: LICENSE
      to: "."
    bin: "node-pod"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/mattfenwick/krew-node-pod/releases/download/v0.1.0/node-pod_windows_amd64.zip
    sha256: ""
    files:
    - from: "/node-pod.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "node-pod.exe"
  shortDescription: A new plugin
  homepage: https://github.com/mattfenwick/krew-node-pod
  caveats: |
    Usage:
      $ kubectl node-pod

    For additional options:
      $ kubectl node-pod --help
      or https://github.com/mattfenwick/krew-node-pod/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
